### ISSUE TITLE
Test the current test

### ISSUE THREAD

**Issue by chalmagean** [tonini/tester.el#2]
In ruby the most common way of running tests is to run the test under the cursor (current test) and then keep running that when you're in different files trying to make it pass (run the last test). Only after those 2 are passing you go ahead and run the whole file/suite.

Are there any plans on supporting that feature/workflow?

**Comment by tonini** [comment]
Actually at the moment `tester` works like you described it. 

Because it stores the last function call under the cursor (current test) it will aways will run this function wherever the user are, until the user switches into a new test file and hit `tester-run-test-file` (because then `tester` realize that there is another test file in the buffer than the stored one).

**Comment by chalmagean** [comment]
oh, nice, I didn't realise that. Thanks!

**Comment by tonini** [comment]
You're welcome. :-)
